#server:
#  port: 8080
#
#spring:
#  application:
#    name: demo
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/todolist_database
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#
#  flyway:
#    baseline-on-migrate: true
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test/todos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # 可选值：none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
