server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/table
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    baseline-on-migrate: true
